### ISSUE TITLE
CI(GitHubActions) 自動テスト

### ISSUE THREAD

**Issue by kamakurayuma** [kamakurayuma/mvp#59]

**Comment by kamakurayuma** [comment]
## 解決したいこと・達成したいものについて

CIテストが失敗しており、こちらのテストを通るようにしたいです。
test内で起きてるエラーは以下の通りです。
`URI::InvalidURIError: bad URI (is not URI?): nil`
`NoMethodError: undefined method 'to_str' for nil (NoMethodError)`

## 聞きたいこと・アドバイスが欲しいこと
URI::InvalidURIError や NoMethodError が発生する原因として、config/database.ymlやci.ymlの記述が誤っていると考えているのですが、これらに関してどのような設定ミスが考えられるか、これらのエラーを解消するためにどのような修正を加えればよいかご教授いただきたいです。

## 実装の際に参考にした資料等
https://qiita.com/maabow/items/25b0d6febcf5e56db30c
↑上記の記事を参考にci.ymlを記述しました。

testで発生している
`URI::InvalidURIError: bad URI (is not URI?): nil`
`NoMethodError: undefined method `to_str' for nil (NoMethodError)`に関しては
該当しそうな記事が見つからなかったためChatGPTで確認したところ
「config/database.yml の設定に問題がある。
具体的には、URI が正しくない、もしくは nil となっているため、URI::InvalidURIError が発生している」
とのことでしたのでdatabase.ymlを確認しました。


## 現状のコードの状態がわかるURL(プルリクエスト・リポジトリ等)
https://github.com/kamakurayuma/mvp/pull/67
https://github.com/kamakurayuma/mvp/actions/runs/12646573917/job/35237500858

## 現状のコードの状態がわかるURLのどこが関係していると考えているのか
ci.ymlかdatabase.yml の設定内容が原因でエラーが発生していると考えています。
`ci.yml`
```
name: CI

on:
  pull_request:
  push:
    branches: [ main ]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: .ruby-version
          bundler-cache: true

      - name: Lint code for consistent style
        run: bin/rubocop -f github

  test:
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql
        env:
          MYSQL_ALLOW_EMPTY_PASSWORD: true
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - name: Install packages
        run: sudo apt-get update && sudo apt-get install --no-install-recommends -y google-chrome-stable curl default-mysql-client libjemalloc2 libvips

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.3.6'
          bundler-cache: true

      - name: Run tests
        env:
          RAILS_ENV: test
          DATABASE_URL: mysql2://127.0.0.1:3306
        run: bin/rails db:test:prepare test test:system

      - name: Keep screenshots from failed system tests
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: screenshots
          path: ${{ github.workspace }}/tmp/screenshots
          if-no-files-found: ignore
```

`database.yml `

```
# MySQL. Versions 5.5.8 and up are supported.
#
# Install the MySQL driver
#   gem install mysql2
#
# Ensure the MySQL gem is defined in your Gemfile
#   gem "mysql2"
#
# And be sure to use new-style password hashing:
#   https://dev.mysql.com/doc/refman/5.7/en/password-hashing.html
#
default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: password
  host: db

development:
  <<: *default
  database: myapp_development

# Warning: The database defined as "test" will be erased and
# re-generated from your development database when you run "rake".
# Do not set this db to the same as development or production.
test:
  <<: *default
  database: myapp_test

# As with config/credentials.yml, you never want to store sensitive information,
# like your database password, in your source code. If your source code is
# ever seen by anyone, they now have access to your database.
#
# Instead, provide the password or a full connection URL as an environment
# variable when you boot the app. For example:
#
#   DATABASE_URL="mysql2://myuser:mypass@localhost/somedatabase"
#
# If the connection URL is provided in the special DATABASE_URL environment
# variable, Rails will automatically merge its configuration values on top of
# the values provided in this file. Alternatively, you can specify a connection
# URL environment variable explicitly:
#
#   production:
#     url: <%= ENV["MY_APP_DATABASE_URL"] %>
#
# Read https://guides.rubyonrails.org/configuring.html#configuring-a-database
# for a full overview on how database connection configuration can be specified.
#
production:
  primary: &primary_production
    <<: *default
    url: <%= ENV['JAWSDB_URL'] %>
    database: <%= URI.parse(ENV['JAWSDB_URL']).path[1..-1] %>
    username: <%= URI.parse(ENV['JAWSDB_URL']).user %>
    password: <%= URI.parse(ENV['JAWSDB_URL']).password %>
    host: <%= URI.parse(ENV['JAWSDB_URL']).host %>
    port: <%= URI.parse(ENV['JAWSDB_URL']).port %>
  cache:
    <<: *primary_production
    database: myapp_production_cache
    migrations_paths: db/cache_migrate
  queue:
    <<: *primary_production
    database: myapp_production_queue
    migrations_paths: db/queue_migrate
  cable:
    <<: *primary_production
    database: myapp_production_cable
    migrations_paths: db/cable_migrate
```

## 検証した結果から分かったこと・考えたこと
DATABASE_URLがnilの関係でCIが通らない？と考え、DATABASE_URLの設定がちゃんとできているか
下記の２つのコマンドで確認してみました。
そうすると、nilだったり、空欄で返ってきたのでここを反映できるようになるとCIテストもうまくいくのではないかと思いました。


```
root@3d742ab7c181:/myapp# rails console
Loading development environment (Rails 8.0.1)
myapp(dev)> ENV['DATABASE_URL']
=> nil
```

```
yuma@tomodachi:~/Projects/mvp$ echo $DATABASE_UR

yuma@tomodachi:~/Projects/mvp$
```
